name: build

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cargo Cache
      uses: actions/cache@v2
      continue-on-error: false
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          cargo-
    - name: Install Advent of Code
      run: cargo install cargo-aoc
    - name: Build
      run: cargo build --verbose
    - name: Advent of Code 🎄
      run: cargo aoc
